// WHATSAPP CUSTOMERS
export const SET_WHATSAPP_CUSTOMERS_REQUEST = 'SET_WHATSAPP_CUSTOMERS_REQUEST';
export const SET_WHATSAPP_CUSTOMERS = 'SET_WHATSAPP_CUSTOMERS';

// FACEBOOK CUSTOMERS
export const SET_CUSTOMERS_REQUEST = 'SET_CUSTOMERS_REQUEST';
export const SET_CUSTOMERS = 'SET_CUSTOMERS';

// LOAD DATA FAILURE
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';
