// WHATSAPP CUSTOMERS
export const SET_WHATSAPP_CUSTOMERS_REQUEST = 'SET_WHATSAPP_CUSTOMERS_REQUEST';
export const SET_WHATSAPP_CUSTOMERS = 'SET_WHATSAPP_CUSTOMERS';

// FACEBOOK CUSTOMERS
export const SET_CUSTOMERS_REQUEST = 'SET_CUSTOMERS_REQUEST';
export const SET_CUSTOMERS = 'SET_CUSTOMERS';

// ML ORDERS
export const SET_ORDERS_REQUEST = 'SET_ORDERS_REQUEST';
export const SET_ORDERS = 'SET_ORDERS';

// LOAD DATA FAILURE
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';

export const ERASE_DEAL = 'ERASE_DEAL';
export const CHANGE_DEAL_COLUMN = 'CHANGE_DEAL_COLUMN';
export const SET_COLUMNS = 'SET_COLUMNS';

// WHATSAPP MESSAGES
export const SET_WHATSAPP_MESSAGES = 'SET_WHATSAPP_MESSAGES';
export const SET_WHATSAPP_MESSAGES_REQUEST = 'SET_WHATSAPP_MESSAGES_REQUEST';

// MESSENGER MESSAGES
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_MESSAGES_REQUEST = 'SET_MESSAGES_REQUEST';

export const ADD_DEALS_TO_COLUMN = 'ADD_DEALS_TO_COLUMN';
