default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: <%= ENV.fetch('MERCATELY_DATABASE_USER') %>
  password: <%= ENV.fetch('APPNAME_DATABASE_PASSWORD') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: mercately_development

test:
  <<: *default
  database: mercately_test

production:
  <<: *default
  database: mercately_production
